name: Dr4Honras
version: 1.0
main: com.dr4gula.Main
api-version: 1.7.10
authors: [ Dr4gula ]
softdepend: [PlaceholderAPI]
commands:
  sethonra:
    description: Adiciona uma quantidade especifica de honra para o player.
    usage: /sethonra <player> <amount>
    permission: dr4honras.manager

  delhonra:
    description: Retira uma quantidade especifica de honra para o player.
    usage: /delhonra <player> <amount>
    permission: dr4honras.manager

  addhonra:
    description: Adiciona uma quantia de honra no valor que o player já tem.
    usage: /addhonra <player> <amount>
    permission: dr4honras.manager

  honrasrank:
    description: O Player consegue verificar em quam ranking de honras está.
    usage: /honrasrank
    permission: dr4honras.use

  honras:
    description: Retira uma quantidade especifica de honra para o player.
    usage: /honras
    permission: dr4honras.use

  honras2x:
    description: Ativa multiplicador de honras por tempo determinado.
    usage: /honras2x <tempo>
    permission: dr4honras.manager